#pragma once
#include "CameraUI.h"
#include "textureManager.h"
#include "collisionsManager.h"
#include "Ennemy.h"
#include "EntityManager.h"
#include "fourches.h"
#include "gameManagment.h"
#include "Ground.h"
#include "map.h"
#include "Menu.h"
#include "panneau.h"
#include "Player.h"
#include "Projectiles.h"
#include "UIButton.h"
#include "UIElements.h"
#include "UIImage.h"
#include "UIManagers.h"
#include "Entity.h"

#include <iostream>
#include <SFML/Graphics.hpp>
#include <vector>
#include <string>
#include <memory>
#include <thread>
#include <fstream>
#include <unordered_map>
#include <stdexcept>